apiVersion: skaffold/v1beta3
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
  - image: docker.io/jenkinsxio/builder-base
    context: .
    docker:
      dockerfile: Dockerfile
  - image: docker.io/jenkinsxio/builder-slim
    context: .
    docker:
      dockerfile: Dockerfile.slim
  - image: docker.io/jenkinsxio/builder-ruby
    context: .
    docker:
      dockerfile: Dockerfile.ruby
  - image: docker.io/jenkinsxio/builder-swift
    context: .
    docker:
      dockerfile: Dockerfile.swift
  kaniko:
    buildContext:
      localDir: {}
#    pullSecretName: kaniko-secret
    namespace: jx
    dockerConfig:
      path: /home/jenkins/.docker/config.json
deploy:
  kubectl:
    manifests:
