apiVersion: skaffold/v1beta3
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
  - image: docker.io/jenkinsxio/builder-python2
    context: .
    docker: {}
test:
- image: docker.io/jenkinsxio/builder-python2
  structureTests:
  - ./test/*
deploy:
  kubectl:
    manifests:
profiles:
- name: local
  build:
    local:
      push: false
- name: kaniko
  build:
    kaniko:
      buildContext:
        gcsBucket: jenkinsx-dev-skaffold-kaniko
      pullSecretName: kaniko-secret
      namespace: jx
      dockerConfig:
        secretName: jenkins-docker-cfg
      image: rawlingsj/executor:dev21
      cache:
        repo: jenkins-x-docker-registry.jx.svc.cluster.local:5000/builder/cache
      flags:
      - --cache-dir=/workspace
